# Generated by Django 5.0.1 on 2026-03-07 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_seed_leave_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.CharField(help_text='Static QR code value for office sticker', max_length=255, unique=True)),
                ('office_name', models.CharField(default='Main Office', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Office Configuration',
            },
        ),
    ]
