# Generated by Django 5.0.1 on 2026-03-12 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_add_office_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='verification_method',
            field=models.CharField(choices=[('face', 'Face Recognition'), ('qr', 'QR Code'), ('location', 'Location'), ('face_qr', 'Face + QR'), ('face_location', 'Face + Location'), ('face_local', 'Face (On-Device) + QR'), ('manual', 'Manual (Admin)')], default='manual', max_length=15),
        ),
    ]
