# Generated by Django 6.0.1 on 2026-03-13 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_add_face_local_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='workassignment',
            name='attachment',
            field=models.FileField(blank=True, help_text='PDF or document attached to this task', null=True, upload_to='employees/work_assignments/'),
        ),
    ]
