# Generated by Django 6.0.1 on 2026-03-13 08:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_workassignment_attachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('instructor', models.CharField(blank=True, help_text='Name of the instructor/trainer', max_length=255)),
                ('location', models.CharField(blank=True, help_text='Room, link, or address', max_length=255)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=12)),
                ('attachment', models.FileField(blank=True, help_text='Study material or agenda', null=True, upload_to='employees/class_materials/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_classes', to=settings.AUTH_USER_MODEL)),
                ('interns', models.ManyToManyField(blank=True, help_text='Leave empty to include all interns', related_name='scheduled_classes', to='employees.employee')),
            ],
            options={
                'verbose_name_plural': 'Scheduled Classes',
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
