# Generated by Django 6.0.1 on 2026-03-13 10:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_scheduledclass'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.IntegerField(help_text='Month (1-12)')),
                ('year', models.IntegerField()),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, help_text='Monthly salary or stipend', max_digits=12)),
                ('working_days', models.IntegerField(default=0, help_text='Total working days in the month')),
                ('days_present', models.IntegerField(default=0)),
                ('days_absent', models.IntegerField(default=0, help_text='Unpaid leave / absent days')),
                ('paid_leave_days', models.IntegerField(default=0)),
                ('unpaid_leave_days', models.IntegerField(default=0)),
                ('leave_deduction', models.DecimalField(decimal_places=2, default=0, help_text='Amount deducted for unpaid leave', max_digits=12)),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deductions', models.DecimalField(decimal_places=2, default=0, help_text='Other deductions (tax, etc.)', max_digits=12)),
                ('net_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('paid', 'Paid')], default='draft', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='employees.employee')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('employee', 'month', 'year')},
            },
        ),
    ]
