# Generated by Django 6.0.1 on 2026-03-14 05:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_payroll'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='commission_percentage',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Default commission percentage (for interns)', max_digits=5),
        ),
        migrations.AddField(
            model_name='employee',
            name='intern_type',
            field=models.CharField(blank=True, choices=[('digital', 'Digital Marketing'), ('field', 'Field Marketing')], default='', help_text='Digital or Field marketing (for interns)', max_length=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('employee', 'Employee'), ('intern', 'Intern'), ('owner', 'Owner'), ('partner', 'Partner')], default='employee', max_length=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='supervisor',
            field=models.ForeignKey(blank=True, help_text='Supervisor (for interns)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_employees', to=settings.AUTH_USER_MODEL),
        ),
    ]
