# Generated by Django 6.0.1 on 2026-03-14 05:12

from django.db import migrations
from django.utils import timezone


def populate_roles_and_intern_data(apps, schema_editor):
    Employee = apps.get_model('employees', 'Employee')
    InternProfile = apps.get_model('crm', 'InternProfile')

    # Set role='intern' for employees with employment_type='intern'
    Employee.objects.filter(employment_type='intern').update(role='intern')

    # Copy intern-specific data from InternProfile to Employee
    for profile in InternProfile.objects.select_related('user').all():
        try:
            employee = Employee.objects.get(user=profile.user)
            employee.intern_type = profile.intern_type
            employee.commission_percentage = profile.default_commission_percentage
            employee.supervisor = profile.supervisor
            if employee.role != 'intern':
                employee.role = 'intern'
            save_fields = ['intern_type', 'commission_percentage', 'supervisor', 'role']
            employee.save(update_fields=save_fields)
        except Employee.DoesNotExist:
            # Create Employee record for InternProfile users who don't have one
            last_emp = Employee.objects.order_by('-employee_id').first()
            if last_emp and last_emp.employee_id.startswith('EMP'):
                try:
                    num = int(last_emp.employee_id[3:]) + 1
                except ValueError:
                    num = 1
            else:
                num = 1
            employee_id = f'EMP{num:03d}'

            Employee.objects.create(
                user=profile.user,
                employee_id=employee_id,
                employment_type='intern',
                role='intern',
                department='marketing',
                designation='Intern',
                intern_type=profile.intern_type,
                commission_percentage=profile.default_commission_percentage,
                supervisor=profile.supervisor,
                status='active' if profile.status == 'active' else 'inactive',
                joining_date=profile.joining_date or timezone.now().date(),
            )

    # Set role='owner' for superusers who have Employee profiles
    User = apps.get_model('auth', 'User')
    for user in User.objects.filter(is_superuser=True):
        Employee.objects.filter(user=user, role='employee').update(role='owner')


def reverse_populate(apps, schema_editor):
    Employee = apps.get_model('employees', 'Employee')
    Employee.objects.all().update(role='employee', intern_type='', commission_percentage=5.00, supervisor=None)


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_add_role_and_intern_fields'),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_roles_and_intern_data, reverse_populate),
    ]
