# Generated by Django 6.0.1 on 2026-03-17 05:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_populate_roles_and_intern_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('certificate_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('verification_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(default='INTERNSHIP CERTIFICATE', help_text='e.g. INTERNSHIP CERTIFICATE, COURSE COMPLETION CERTIFICATE', max_length=200)),
                ('salutation', models.CharField(choices=[('Mr.', 'Mr.'), ('Ms.', 'Ms.'), ('Mrs.', 'Mrs.')], default='Mr.', max_length=10)),
                ('student_name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10)),
                ('college_name', models.CharField(blank=True, max_length=300)),
                ('course_name', models.CharField(help_text='e.g. Web Development Internship', max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('duration_days', models.PositiveIntegerField(help_text='Total duration in days')),
                ('mode', models.CharField(choices=[('offline', 'Offline'), ('online', 'Online'), ('hybrid', 'Hybrid')], default='offline', max_length=10)),
                ('skills', models.JSONField(default=list, help_text='List of skills learned, e.g. ["HTML5 and CSS3", "JavaScript"]')),
                ('closing_text', models.TextField(default='actively participated in all training sessions, hands-on tasks, and project assignments, demonstrating dedication, teamwork, and a strong interest in learning modern web technologies.', help_text='Closing paragraph text (pronoun auto-applied)')),
                ('wish_text', models.TextField(default='We wish {pronoun} success in {possessive} future academic and professional endeavors.', help_text='Use {pronoun} for him/her and {possessive} for his/her')),
                ('date_of_issuance', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
