# Generated by Django 6.0.1 on 2026-03-17 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='certificate_type',
            field=models.CharField(choices=[('inter', 'Internship'), ('exp', 'Experience'), ('course', 'Course Completion'), ('merit', 'Merit'), ('particip', 'Participation')], default='inter', help_text='Determines ref number prefix and default title', max_length=10),
        ),
    ]
