# Generated by Django 6.0.1 on 2026-03-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_certificate_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='duration_days',
            field=models.PositiveIntegerField(blank=True, help_text='Total duration in days', null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
