# Generated by Django 6.0.1 on 2026-03-17 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0013_alter_certificate_duration_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='closing_text',
        ),
        migrations.AddField(
            model_name='certificate',
            name='body_text',
            field=models.TextField(blank=True, help_text='Full certificate body content. Use placeholders: {salutation}, {student_name}, {college_name}, {course_name}, {start_date}, {end_date}, {duration_days}, {mode}, {skills}, {pronoun} (he/she), {pronoun_cap} (He/She), {possessive} (his/her), {object_pronoun} (him/her)'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='skills',
            field=models.JSONField(blank=True, default=list, help_text='List of skills (rendered as bullet points in body_text {skills} placeholder)'),
        ),
    ]
