# Generated by Django 6.0.1 on 2026-03-17 10:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0014_remove_certificate_closing_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. Internship - Student, Internship - Professional', max_length=200)),
                ('certificate_type', models.CharField(choices=[('inter', 'Internship'), ('exp', 'Experience'), ('course', 'Course Completion'), ('merit', 'Merit'), ('particip', 'Participation')], default='inter', max_length=10)),
                ('title', models.CharField(help_text='Certificate title, e.g. INTERNSHIP CERTIFICATE', max_length=200)),
                ('body_text', models.TextField(help_text='Certificate body with placeholders: {salutation}, {student_name}, {college_name}, {course_name}, {start_date}, {end_date}, {duration_days}, {mode}, {skills}, {pronoun}, {pronoun_cap}, {possessive}, {object_pronoun}')),
                ('wish_text', models.TextField(default='We wish {pronoun} success in {possessive} future academic and professional endeavors.', help_text='Use {pronoun} for him/her and {possessive} for his/her')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['certificate_type', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate_type',
            field=models.CharField(choices=[('inter', 'Internship'), ('exp', 'Experience'), ('course', 'Course Completion'), ('merit', 'Merit'), ('particip', 'Participation')], default='inter', help_text='Determines ref number prefix', max_length=10),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='title',
            field=models.CharField(default='INTERNSHIP CERTIFICATE', max_length=200),
        ),
        migrations.AddField(
            model_name='certificate',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Template used - body_text is copied from template on create', null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.certificatetemplate'),
        ),
    ]
