# Generated by Django 6.0.1 on 2026-03-19 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0015_certificatetemplate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workassignment',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='workassignment',
            name='assigned_to',
            field=models.ManyToManyField(related_name='work_assignments', to='employees.employee'),
        ),
    ]
