# Generated by Django 6.0.1 on 2026-03-19 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0016_remove_workassignment_assigned_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workassignment',
            name='confidentiality_disclaimer',
            field=models.TextField(blank=True, help_text='Confidentiality notice or disclaimer shown to assigned employees'),
        ),
    ]
