# Generated by Django 6.0.1 on 2026-03-26 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0017_workassignment_confidentiality_disclaimer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='course_name',
            field=models.CharField(blank=True, help_text='e.g. Web Development Internship', max_length=200),
        ),
    ]
