# Generated by Django 6.0.1 on 2026-04-11 04:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0018_make_course_name_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='is_force_checkout',
            field=models.BooleanField(default=False, help_text='True if employee force-checked-out before completing required hours'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_remote',
            field=models.BooleanField(default=False, help_text='True if checked in remotely (hybrid/remote employees)'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='pending_hours',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Shortfall = required_hours - worked_hours (0 if worked >= required)', max_digits=5),
        ),
        migrations.AddField(
            model_name='attendance',
            name='required_hours',
            field=models.DecimalField(decimal_places=2, default=6.0, help_text='Required working hours for this day (snapshot from OfficeConfig)', max_digits=4),
        ),
        migrations.AddField(
            model_name='attendance',
            name='worked_hours',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual hours worked, set at check-out', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_mode',
            field=models.CharField(choices=[('onsite', 'Onsite'), ('hybrid', 'Hybrid'), ('remote', 'Remote')], default='onsite', help_text='Onsite, Hybrid, or fully Remote. Hybrid/remote can check in without QR/geo-fence.', max_length=10),
        ),
        migrations.AddField(
            model_name='officeconfig',
            name='check_in_deadline',
            field=models.TimeField(default=datetime.time(10, 15), help_text='Check-in cutoff time. After this only admin can add check-in.'),
        ),
        migrations.AddField(
            model_name='officeconfig',
            name='daily_required_hours',
            field=models.DecimalField(decimal_places=2, default=6.0, help_text='Required working hours per day (default 6)', max_digits=4),
        ),
        migrations.AddField(
            model_name='officeconfig',
            name='min_checkout_time_floor',
            field=models.TimeField(default=datetime.time(16, 0), help_text='Earliest time employees may check out (e.g. 4:00 PM)'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='total_pending_hours',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Sum of shortfall hours across the month (from Attendance.pending_hours)', max_digits=7),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='verification_method',
            field=models.CharField(choices=[('face', 'Face Recognition'), ('qr', 'QR Code'), ('location', 'Location'), ('face_qr', 'Face + QR'), ('face_location', 'Face + Location'), ('face_local', 'Face (On-Device) + QR'), ('remote', 'Remote (Face only)'), ('manual', 'Manual (Admin)')], default='manual', max_length=15),
        ),
    ]
