# Generated by Django 6.0.1 on 2026-06-09 10:06

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0020_latecheckingrant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InternAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='e.g. "Aptitude Test 1"', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField(default=django.utils.timezone.localdate, help_text='Date the test was taken')),
                ('max_score', models.DecimalField(decimal_places=2, help_text='Total marks (out of)', max_digits=6)),
                ('scored', models.DecimalField(blank=True, decimal_places=2, help_text='Marks the intern scored (leave blank if not yet graded)', max_digits=6, null=True)),
                ('test_file', models.FileField(blank=True, help_text='The test paper (PDF)', null=True, upload_to='employees/assessments/papers/')),
                ('answer_key_file', models.FileField(blank=True, help_text='The answer key (PDF) — visible to the intern', null=True, upload_to='employees/assessments/answer_keys/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assessments', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(help_text='The intern this assessment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Intern Assessment',
                'verbose_name_plural': 'Intern Assessments',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
