# Generated by Django 6.0.1 on 2026-07-15 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0021_internassessment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='body_text',
            field=models.TextField(blank=True, help_text='Full certificate body content. Use placeholders: {salutation}, {student_name}, {college_name}, {course_name}, {position} (alias of course_name), {start_date}, {end_date}, {duration_days}, {mode}, {skills}, {pronoun} (he/she), {pronoun_cap} (He/She), {possessive} (his/her), {object_pronoun} (him/her). Unknown placeholders render literally.'),
        ),
    ]
