# Generated by Django 6.0.1 on 2026-07-15 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0022_alter_certificate_body_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='position',
            field=models.CharField(blank=True, help_text='Role held, e.g. Flutter Developer Intern ({position}). Falls back to course_name when blank.', max_length=200),
        ),
        migrations.AddField(
            model_name='certificate',
            name='register_number',
            field=models.CharField(blank=True, help_text='College/university register number, e.g. BAI247966 ({register_number})', max_length=50),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='body_text',
            field=models.TextField(blank=True, help_text='Full certificate body content. Use placeholders: {salutation}, {student_name}, {register_number}, {college_name}, {course_name}, {position}, {start_date}, {end_date}, {duration_days}, {mode}, {skills}, {pronoun} (he/she), {pronoun_cap} (He/She), {possessive} (his/her), {object_pronoun} (him/her). Unknown placeholders render literally.'),
        ),
    ]
