# Generated by Django 6.0.1 on 2026-08-29 07:01

import django.db.models.deletion
import employees.agreement_models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0023_certificate_position_certificate_register_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgreementTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('version', models.CharField(default='v1.0', max_length=20)),
                ('agreement_type', models.CharField(choices=[('internship_continuation', 'Internship Continuation'), ('other', 'Other')], default='internship_continuation', max_length=30)),
                ('heading', models.CharField(default='Internship Continuation & Learning Agreement', help_text='Large title at the top of the document', max_length=200)),
                ('eyebrow', models.CharField(blank=True, default='INTERNSHIP CONTINUATION CONFIRMATION', help_text='Small label above the title', max_length=100)),
                ('intro_html', models.TextField(blank=True, help_text='Opening paragraphs, one per line')),
                ('sections', models.JSONField(blank=True, default=list, help_text='[{"no": 1, "title": "...", "body": "...", "bullets": [...], "callout": {"style": "info|warn|dark", "text": "..."}}]')),
                ('monthly_fee', models.DecimalField(blank=True, decimal_places=2, help_text='Monthly internship fee, e.g. 750.00', max_digits=10, null=True)),
                ('fee_in_words', models.CharField(blank=True, max_length=200)),
                ('fee_note', models.CharField(blank=True, help_text='Small print under the fee, e.g. applicable for each month', max_length=300)),
                ('confirmation_html', models.TextField(blank=True, help_text='Final confirmation callout, shown just above the form')),
                ('continue_label', models.CharField(default='Continue my internship', max_length=100)),
                ('decline_label', models.CharField(default='Discontinue my internship', max_length=100)),
                ('require_college_fields', models.BooleanField(default=True, help_text='Ask for College / Course / Domain. Interns yes; overridden off for non-interns.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AgreementRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, default=employees.agreement_models.generate_token, help_text='Secret in the public URL', max_length=64, unique=True)),
                ('reference', models.CharField(blank=True, db_index=True, help_text='Human-readable ref, e.g. RT/AGR/26/0007', max_length=40)),
                ('snapshot_json', models.JSONField(blank=True, default=dict)),
                ('snapshot_version', models.CharField(blank=True, max_length=20)),
                ('snapshot_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Sent'), ('viewed', 'Opened'), ('accepted', 'Continuing'), ('declined', 'Discontinued'), ('cancelled', 'Cancelled'), ('superseded', 'Superseded')], db_index=True, default='pending', max_length=12)),
                ('batch', models.UUIDField(blank=True, db_index=True, help_text='Groups links generated in one send', null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=employees.agreement_models.default_expiry)),
                ('first_viewed_at', models.DateTimeField(blank=True, null=True)),
                ('last_viewed_at', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('decision', models.CharField(blank=True, choices=[('continue', 'Continue'), ('discontinue', 'Discontinue')], max_length=12)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('college_name', models.CharField(blank=True, max_length=300)),
                ('course_department', models.CharField(blank=True, max_length=200)),
                ('internship_domain', models.CharField(blank=True, max_length=200)),
                ('signed_name', models.CharField(blank=True, help_text='Typed signature - this is the binding one', max_length=200)),
                ('signature_image', models.ImageField(blank=True, help_text='Optional drawn signature', null=True, upload_to='agreements/signatures/')),
                ('signed_date', models.DateField(blank=True, null=True)),
                ('agreed_to_terms', models.BooleanField(default=False)),
                ('decline_reason', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('body_hash', models.CharField(blank=True, help_text='SHA-256 of the snapshot the signer agreed to', max_length=64)),
                ('hr_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agreement_requests', to='employees.employee')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agreements_sent', to=settings.AUTH_USER_MODEL)),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='employees.agreementrequest')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='employees.agreementtemplate')),
            ],
            options={
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['employee', 'status'], name='employees_a_employe_a97207_idx'), models.Index(fields=['batch'], name='employees_a_batch_30bb12_idx')],
            },
        ),
    ]
