# Generated by Django 6.0.1 on 2026-08-29 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0025_seed_internship_agreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreementtemplate',
            name='confirmation_free_html',
            field=models.TextField(blank=True, help_text='Confirmation callout used when the internship carries no monthly fee. Falls back to confirmation_html when blank.'),
        ),
    ]
