# Generated by Django 6.0.1 on 2026-09-02 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0027_agreement_free_internship_wording'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='force_checkout_reason',
            field=models.TextField(blank=True, help_text='Why this person left before completing the required hours'),
        ),
        migrations.AddField(
            model_name='employee',
            name='custom_check_in_deadline',
            field=models.TimeField(blank=True, help_text='Personal check-in cutoff (e.g. 12:00). Blank = office default.', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='custom_checkout_time_floor',
            field=models.TimeField(blank=True, help_text='Earliest time this person may check out (e.g. 18:00). Blank = office default.', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='custom_required_hours',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Required working hours per day for this person. Blank = office default.', max_digits=4, null=True),
        ),
    ]
