# Generated by Django 6.0.1 on 2026-09-07 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0028_attendance_force_checkout_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreementtemplate',
            name='accept_confirm_text',
            field=models.CharField(default='I confirm I have read and understood the terms, and I agree to continue my internship', help_text='Checkbox beside the signature. The money sentence is appended to it.', max_length=300),
        ),
        migrations.AddField(
            model_name='agreementtemplate',
            name='accept_statement',
            field=models.CharField(default='I wish to continue my internship', help_text='The YES line recorded in the signed copy.', max_length=200),
        ),
        migrations.AddField(
            model_name='agreementtemplate',
            name='decision_heading',
            field=models.CharField(default='Continuation Decision', help_text='Heading above the YES / NO buttons.', max_length=120),
        ),
        migrations.AddField(
            model_name='agreementtemplate',
            name='decline_button_label',
            field=models.CharField(default='Confirm discontinuation', max_length=100),
        ),
        migrations.AddField(
            model_name='agreementtemplate',
            name='decline_heading',
            field=models.CharField(default='Discontinue Internship', max_length=120),
        ),
        migrations.AddField(
            model_name='agreementtemplate',
            name='decline_intro',
            field=models.TextField(default='You are about to inform Ralfiz Technologies that you do not wish to continue your internship.', help_text='Shown above the reason box on the decline panel.'),
        ),
        migrations.AddField(
            model_name='agreementtemplate',
            name='decline_statement',
            field=models.CharField(default='I do not wish to continue my internship', help_text='The NO line recorded in the signed copy.', max_length=200),
        ),
        migrations.AddField(
            model_name='agreementtemplate',
            name='money_agreed_note',
            field=models.CharField(blank=True, default='Agreed to the monthly internship fee of {amount}.', help_text='Recorded in the signed copy when an amount applies. {amount} is filled in.', max_length=200),
        ),
        migrations.AddField(
            model_name='agreementtemplate',
            name='money_confirm_suffix',
            field=models.CharField(blank=True, default='and to pay the applicable {amount} monthly internship fee', help_text='Appended to the checkbox when an amount applies. {amount} is filled in.', max_length=200),
        ),
        migrations.AddField(
            model_name='agreementtemplate',
            name='no_money_note',
            field=models.CharField(blank=True, default='This internship carries no monthly fee.', help_text='Recorded in the signed copy when there is no amount.', max_length=200),
        ),
        migrations.AlterField(
            model_name='agreementtemplate',
            name='agreement_type',
            field=models.CharField(choices=[('internship_continuation', 'Internship Continuation'), ('internship_new_joinee', 'Internship - New Joinee'), ('other', 'Other')], default='internship_continuation', max_length=30),
        ),
    ]
