# Generated by Django 6.0.1 on 2026-09-07 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0029_agreementtemplate_accept_confirm_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreementtemplate',
            name='accept_sub',
            field=models.CharField(default='with Ralfiz Technologies', help_text='Small print under the YES button in the numbered decision section.', max_length=120),
        ),
        migrations.AddField(
            model_name='agreementtemplate',
            name='decline_sub',
            field=models.CharField(default='end participation in the program', help_text='Small print under the NO button in the numbered decision section.', max_length=120),
        ),
    ]
