# Generated by Django 6.0.1 on 2026-09-07 06:59

import employees.agreement_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0030_agreementtemplate_accept_sub_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreementrequest',
            name='snapshot_money_mode',
            field=models.CharField(choices=[('fee', 'Intern pays a monthly fee'), ('stipend', 'We pay the intern a monthly stipend'), ('none', 'Free - no fee and no stipend')], default='fee', help_text='Which way the money went for this person: fee, stipend, or neither.', max_length=10),
        ),
        migrations.AddField(
            model_name='agreementtemplate',
            name='money_copy',
            field=models.JSONField(blank=True, default=employees.agreement_models.default_money_copy, help_text='Wording for each money arrangement (fee / stipend / none). The block for the chosen mode replaces the section marked show_fee.'),
        ),
        migrations.AddField(
            model_name='agreementtemplate',
            name='money_mode',
            field=models.CharField(choices=[('fee', 'Intern pays a monthly fee'), ('stipend', 'We pay the intern a monthly stipend'), ('none', 'Free - no fee and no stipend')], default='fee', help_text='Default arrangement. HR can pick a different one per person when sending.', max_length=10),
        ),
    ]
