# Generated by Django 6.0.1 on 2026-09-07 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0031_agreementrequest_snapshot_money_mode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agreementtemplate',
            name='money_agreed_note',
        ),
        migrations.RemoveField(
            model_name='agreementtemplate',
            name='money_confirm_suffix',
        ),
        migrations.RemoveField(
            model_name='agreementtemplate',
            name='no_money_note',
        ),
    ]
