# Generated by Django 6.0.1 on 2026-09-07 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0032_remove_agreementtemplate_money_agreed_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreementtemplate',
            name='accepted_pill',
            field=models.CharField(default='Continuing', help_text='Outcome shown on the thank-you page when they say yes.', max_length=60),
        ),
        migrations.AddField(
            model_name='agreementtemplate',
            name='declined_pill',
            field=models.CharField(default='Discontinued', help_text='Outcome shown on the thank-you page when they say no.', max_length=60),
        ),
        migrations.AddField(
            model_name='agreementtemplate',
            name='done_accepted_html',
            field=models.TextField(default='Your confirmation to <strong>continue your internship</strong> with Ralfiz Technologies has been recorded. Our team will be in touch about the next steps.', help_text='Thank-you paragraph after they say yes.'),
        ),
        migrations.AddField(
            model_name='agreementtemplate',
            name='done_declined_html',
            field=models.TextField(default='We have noted that you do not wish to continue your internship. Thank you for letting us know, and we wish you all the best.', help_text='Paragraph after they say no.'),
        ),
        migrations.AlterField(
            model_name='agreementrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Sent'), ('viewed', 'Opened'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('cancelled', 'Cancelled'), ('superseded', 'Superseded')], db_index=True, default='pending', max_length=12),
        ),
    ]
