# Generated by Django 6.0.1 on 2026-09-07 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0033_agreementtemplate_accepted_pill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreementtemplate',
            name='college_fields_optional',
            field=models.BooleanField(default=False, help_text='Ask for College and Course but let them be left blank. For agreements sent to people who may not be studying. The internship domain is still required.'),
        ),
    ]
