# Generated by Django 6.0.1 on 2026-10-09 04:27

import django.db.models.deletion
import employees.enrolment_models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0035_dailyreport_dailyreportcomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InternEnrolment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, default=employees.enrolment_models.generate_enrolment_token, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('sent', 'Link sent'), ('opened', 'Opened'), ('submitted', 'To review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='sent', max_length=12)),
                ('invite_name', models.CharField(max_length=200)),
                ('invite_phone', models.CharField(blank=True, max_length=20)),
                ('invite_email', models.EmailField(blank=True, max_length=254)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=employees.enrolment_models.default_enrolment_expiry)),
                ('first_opened_at', models.DateTimeField(blank=True, null=True)),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True)),
                ('guardian_name', models.CharField(blank=True, max_length=200)),
                ('guardian_phone', models.CharField(blank=True, max_length=20)),
                ('college_name', models.CharField(blank=True, max_length=300)),
                ('course', models.CharField(blank=True, help_text='Course and branch, e.g. B.Tech CSE', max_length=200)),
                ('year_of_study', models.CharField(blank=True, choices=[('1', '1st year'), ('2', '2nd year'), ('3', '3rd year'), ('4', '4th year'), ('5', '5th year'), ('graduated', 'Graduated')], max_length=10)),
                ('register_number', models.CharField(blank=True, max_length=50)),
                ('track', models.CharField(blank=True, choices=[('development', 'Software Development'), ('design', 'UI/UX & Graphic Design'), ('digital_marketing', 'Digital Marketing'), ('data', 'Data Analytics'), ('other', 'Other')], max_length=20)),
                ('track_other', models.CharField(blank=True, max_length=200)),
                ('preferred_start_date', models.DateField(blank=True, null=True)),
                ('duration_months', models.CharField(blank=True, choices=[('1', '1 month'), ('2', '2 months'), ('3', '3 months'), ('6', '6 months')], max_length=2)),
                ('work_mode', models.CharField(blank=True, choices=[('onsite', 'Onsite (at our office)'), ('hybrid', 'Hybrid'), ('remote', 'Remote')], max_length=10)),
                ('skills', models.TextField(blank=True, help_text='What the student already knows')),
                ('photo', models.ImageField(blank=True, storage=employees.enrolment_models.private_storage, upload_to=employees.enrolment_models.enrolment_photo_path)),
                ('id_proof', models.FileField(blank=True, storage=employees.enrolment_models.private_storage, upload_to=employees.enrolment_models.enrolment_id_proof_path)),
                ('resume', models.FileField(blank=True, storage=employees.enrolment_models.private_storage, upload_to=employees.enrolment_models.enrolment_resume_path)),
                ('college_letter', models.FileField(blank=True, storage=employees.enrolment_models.private_storage, upload_to=employees.enrolment_models.enrolment_college_letter_path)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('hr_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrolments_sent', to=settings.AUTH_USER_MODEL)),
                ('employee', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrolment', to='employees.employee')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrolments_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
