# Generated by Django 6.0.1 on 2026-10-09 04:46

import employees.enrolment_models
from django.db import migrations, models


#: Area codes used before areas became editable, mapped to their names.
OLD_TRACKS = {
    'development': 'Software Development',
    'design': 'UI/UX & Graphic Design',
    'digital_marketing': 'Digital Marketing',
    'data': 'Data Analytics',
    'other': 'Other',
}


def track_codes_to_names(apps, schema_editor):
    InternEnrolment = apps.get_model('employees', 'InternEnrolment')
    for code, name in OLD_TRACKS.items():
        InternEnrolment.objects.filter(track=code).update(track=name)


def track_names_to_codes(apps, schema_editor):
    InternEnrolment = apps.get_model('employees', 'InternEnrolment')
    for code, name in OLD_TRACKS.items():
        InternEnrolment.objects.filter(track=name).update(track=code)


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0036_intern_enrolment'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrolmentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_modes', models.JSONField(default=employees.enrolment_models.default_work_modes, help_text='Keys from WORK_MODE_CHOICES to offer')),
                ('tracks', models.JSONField(default=employees.enrolment_models.default_tracks, help_text='[{"label": ..., "department": Employee department}]')),
                ('allow_other_track', models.BooleanField(default=True, help_text='Offer "Other" with a free-text area')),
                ('durations', models.JSONField(default=employees.enrolment_models.default_durations, help_text='Month counts to offer')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Enrolment settings',
                'verbose_name_plural': 'Enrolment settings',
            },
        ),
        migrations.AlterField(
            model_name='internenrolment',
            name='duration_months',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='internenrolment',
            name='track',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.RunPython(track_codes_to_names, track_names_to_codes),
    ]
