# Generated by Django 5.0.1 on 2026-01-12 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysettings',
            name='logo',
            field=models.FileField(blank=True, help_text='Accepts PNG, JPG, or SVG files', upload_to='company/'),
        ),
    ]
