# Generated by Django 5.0.1 on 2026-01-12 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_change_logo_to_filefield'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='hsn_code',
            field=models.CharField(blank=True, help_text='HSN code for goods or SAC code for services', max_length=20, verbose_name='HSN/SAC Code'),
        ),
    ]
