# Generated by Django 5.0.1 on 2026-01-12 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_user_to_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='employment_type',
            field=models.CharField(choices=[('permanent', 'Permanent'), ('freelancer', 'Freelancer')], default='permanent', max_length=20),
        ),
        migrations.AddField(
            model_name='teammember',
            name='monthly_salary',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='For permanent employees', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='For freelancers', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(choices=[('developer', 'Developer'), ('designer', 'Designer'), ('project_manager', 'Project Manager'), ('qa', 'QA Engineer'), ('devops', 'DevOps'), ('other', 'Other')], default='developer', max_length=20),
        ),
    ]
