# Generated by Django 5.0.1 on 2026-01-12 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_employment_type_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='team_members',
            field=models.ManyToManyField(blank=True, related_name='assigned_projects', to='core.teammember'),
        ),
    ]
