# Generated by Django 5.0.1 on 2026-01-14 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_change_tax_rate_default_to_zero'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='default_payment_terms',
            field=models.CharField(blank=True, default='50-50', help_text='Default payment terms for quotes', max_length=50),
        ),
        migrations.AddField(
            model_name='quote',
            name='deliverables',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='duration',
            field=models.CharField(blank=True, help_text='e.g., 4-6 weeks', max_length=100),
        ),
        migrations.AddField(
            model_name='quote',
            name='payment_terms',
            field=models.CharField(blank=True, default='50-50', max_length=50),
        ),
        migrations.AddField(
            model_name='quote',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
