# Generated by Django 5.0.1 on 2026-01-14 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_companysettings_default_payment_terms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='default_quote_validity_days',
            field=models.IntegerField(default=30, help_text='Default number of days a quote is valid'),
        ),
    ]
