# Generated by Django 5.0.1 on 2026-01-20 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_companysettings_default_quote_validity_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='invoice_starting_number',
            field=models.IntegerField(default=201, help_text='Starting number for invoices (used when no invoices exist)'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='invoice_prefix',
            field=models.CharField(default='INVRT', help_text='Prefix for invoice numbers (e.g., INVRT)', max_length=10),
        ),
    ]
