# Generated by Django 5.0.1 on 2026-01-25 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_companysettings_invoice_starting_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='google_client_id',
            field=models.CharField(blank=True, help_text='Desktop app client ID from Google Cloud Console', max_length=200, verbose_name='Google OAuth Client ID'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='google_client_id_android',
            field=models.CharField(blank=True, help_text='Android app client ID (if different)', max_length=200, verbose_name='Google OAuth Client ID (Android)'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='google_client_id_ios',
            field=models.CharField(blank=True, help_text='iOS app client ID (if different)', max_length=200, verbose_name='Google OAuth Client ID (iOS)'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='google_reversed_client_id',
            field=models.CharField(blank=True, help_text='For iOS URL scheme (com.googleusercontent.apps.XXX)', max_length=200, verbose_name='Reversed Client ID'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='retailease_force_update',
            field=models.BooleanField(default=False, verbose_name='Force Update'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='retailease_google_drive_enabled',
            field=models.BooleanField(default=True, verbose_name='Google Drive Backup'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='retailease_latest_version',
            field=models.CharField(default='1.0.0', max_length=20, verbose_name='Latest App Version'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='retailease_local_backup_enabled',
            field=models.BooleanField(default=True, verbose_name='Local Backup'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='retailease_maintenance_message',
            field=models.TextField(blank=True, verbose_name='Maintenance Message'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='retailease_maintenance_mode',
            field=models.BooleanField(default=False, verbose_name='Maintenance Mode'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='retailease_min_version',
            field=models.CharField(default='1.0.0', max_length=20, verbose_name='Min App Version'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='retailease_server_backup_enabled',
            field=models.BooleanField(default=True, verbose_name='Server Backup'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='retailease_support_email',
            field=models.EmailField(default='support@ralfizdigital.in', max_length=254, verbose_name='Support Email'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='retailease_support_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Support Phone'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='retailease_support_whatsapp',
            field=models.CharField(blank=True, max_length=20, verbose_name='Support WhatsApp'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='retailease_update_url',
            field=models.URLField(blank=True, verbose_name='App Update URL'),
        ),
    ]
