# Generated by Django 5.0.1 on 2026-01-25 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_client_google_client_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='google_client_secret',
            field=models.CharField(blank=True, help_text='Client Secret for desktop OAuth (required for macOS/Windows/Linux)', max_length=200, verbose_name='Google OAuth Client Secret'),
        ),
    ]
