# Generated by Django 5.0.1 on 2026-02-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_add_google_client_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='client_notes',
            field=models.TextField(blank=True, help_text='Notes visible to the client on the quote'),
        ),
        migrations.AlterField(
            model_name='client',
            name='google_client_id',
            field=models.CharField(blank=True, help_text='OAuth 2.0 Client ID for Windows/Linux (Desktop type in Google Cloud Console)', max_length=200, verbose_name='Google OAuth Client ID (Desktop)'),
        ),
        migrations.AlterField(
            model_name='client',
            name='google_client_id_ios',
            field=models.CharField(blank=True, help_text='OAuth 2.0 Client ID for iOS & macOS (iOS type in Google Cloud Console)', max_length=200, verbose_name='Google OAuth Client ID (iOS/macOS)'),
        ),
        migrations.AlterField(
            model_name='client',
            name='google_client_secret',
            field=models.CharField(blank=True, help_text='Client Secret for Windows/Linux only (not needed for iOS/macOS/Android)', max_length=200, verbose_name='Google OAuth Client Secret'),
        ),
        migrations.AlterField(
            model_name='client',
            name='google_reversed_client_id',
            field=models.CharField(blank=True, help_text='e.g., com.googleusercontent.apps.xxxxx - Used for URL scheme callback', max_length=200, verbose_name='Reversed Client ID (for iOS/macOS)'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='google_client_id',
            field=models.CharField(blank=True, help_text='OAuth 2.0 Client ID for Windows/Linux (Desktop type in Google Cloud Console)', max_length=200, verbose_name='Google OAuth Client ID (Desktop)'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='google_client_id_android',
            field=models.CharField(blank=True, help_text='OAuth 2.0 Client ID for Android (Android type in Google Cloud Console)', max_length=200, verbose_name='Google OAuth Client ID (Android)'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='google_client_id_ios',
            field=models.CharField(blank=True, help_text='OAuth 2.0 Client ID for iOS & macOS (iOS type in Google Cloud Console)', max_length=200, verbose_name='Google OAuth Client ID (iOS/macOS)'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='google_reversed_client_id',
            field=models.CharField(blank=True, help_text='e.g., com.googleusercontent.apps.xxxxx - Used for URL scheme callback', max_length=200, verbose_name='Reversed Client ID (for iOS/macOS)'),
        ),
    ]
