# Generated by Django 5.0.1 on 2026-02-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_quote_client_notes_alter_client_google_client_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='client_notes',
            field=models.TextField(blank=True, help_text='Notes visible to the client on the invoice'),
        ),
    ]
