# Generated by Django 6.0.1 on 2026-03-26 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_make_invoice_number_editable'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='interiodesk_force_update',
            field=models.BooleanField(default=False, verbose_name='InterioDesk Force Update'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='interiodesk_latest_version',
            field=models.CharField(default='1.0.0', max_length=20, verbose_name='InterioDesk Latest Version'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='interiodesk_maintenance_message',
            field=models.TextField(blank=True, verbose_name='InterioDesk Maintenance Message'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='interiodesk_maintenance_mode',
            field=models.BooleanField(default=False, verbose_name='InterioDesk Maintenance Mode'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='interiodesk_min_version',
            field=models.CharField(default='1.0.0', max_length=20, verbose_name='InterioDesk Min Version'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='interiodesk_release_notes',
            field=models.TextField(blank=True, verbose_name='InterioDesk Release Notes'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='interiodesk_update_url_macos',
            field=models.URLField(blank=True, verbose_name='InterioDesk Update URL (macOS)'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='interiodesk_update_url_windows',
            field=models.URLField(blank=True, verbose_name='InterioDesk Update URL (Windows)'),
        ),
    ]
