# Generated by Django 6.0.1 on 2026-03-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_companysettings_interiodesk_force_update_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='interiodesk_file_macos',
            field=models.FileField(blank=True, upload_to='interiodesk/releases/', verbose_name='InterioDesk macOS Installer (.dmg)'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='interiodesk_file_windows',
            field=models.FileField(blank=True, upload_to='interiodesk/releases/', verbose_name='InterioDesk Windows Installer (.exe)'),
        ),
    ]
