# Generated by Django 6.0.1 on 2026-04-07 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_client_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(choices=[('developer', 'Developer'), ('designer', 'Designer'), ('project_manager', 'Project Manager'), ('qa', 'QA Engineer'), ('devops', 'DevOps'), ('digital_marketing', 'Digital Marketing'), ('growth_outreach', 'Growth and Outreach Executive'), ('other', 'Other')], default='developer', max_length=20),
        ),
    ]
