# Generated by Django 6.0.1 on 2026-04-07 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_teammember_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='employment_type',
            field=models.CharField(choices=[('permanent', 'Permanent'), ('contract', 'Contract'), ('freelancer', 'Freelancer')], default='permanent', max_length=20),
        ),
    ]
