# Generated by Django 6.0.1 on 2026-04-16 13:07

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_taskcomment_taskissue_taskactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='last_renewed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='amc_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Agreed AMC amount', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='amc_billing_cycle',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('half_yearly', 'Half Yearly'), ('yearly', 'Yearly')], max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='completion_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='deliverables',
            field=models.TextField(blank=True, help_text='List of deliverables (one per line)'),
        ),
        migrations.AddField(
            model_name='project',
            name='warranty_period',
            field=models.IntegerField(blank=True, help_text='Warranty period in months', null=True),
        ),
        migrations.CreateModel(
            name='AMCContract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('annual_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('half_yearly', 'Half Yearly'), ('yearly', 'Yearly')], default='yearly', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('next_due_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('auto_renew', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amc_contracts', to='core.project')),
            ],
            options={
                'ordering': ['next_due_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AMCPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('upi', 'UPI'), ('cash', 'Cash'), ('card', 'Credit/Debit Card'), ('cheque', 'Cheque'), ('other', 'Other')], default='bank_transfer', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.amccontract')),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='CredentialRenewal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('renewed_date', models.DateField(default=django.utils.timezone.now)),
                ('old_expiry', models.DateField(blank=True, null=True)),
                ('new_expiry', models.DateField()),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewal_history', to='core.credential')),
            ],
            options={
                'ordering': ['-renewed_date'],
            },
        ),
    ]
