# Generated by Django 6.0.1 on 2026-04-17 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_credential_last_renewed_date_project_amc_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amccontract',
            name='contract_type',
            field=models.CharField(choices=[('amc', 'AMC'), ('content_update', 'Content Update'), ('hosting', 'Hosting'), ('seo', 'SEO / Marketing'), ('support', 'Support Plan'), ('other', 'Other')], default='amc', max_length=20),
        ),
    ]
