# Generated by Django 6.0.1 on 2026-04-20 05:52

import core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_amccontract_contract_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectFeature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='core.projecttype')),
            ],
            options={
                'ordering': ['project_type', 'sort_order', 'label'],
                'unique_together': {('project_type', 'label')},
            },
        ),
        migrations.CreateModel(
            name='FeatureRequestLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Opaque token used in the shareable URL', unique=True)),
                ('otp', models.CharField(default=core.models._gen_otp, help_text='6-digit OTP shown to the admin; shared manually with the client', max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('client_notes', models.TextField(blank=True, help_text='Free-form notes from the client')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_request_links', to='core.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_feature_request_links', to=settings.AUTH_USER_MODEL)),
                ('selected_features', models.ManyToManyField(blank=True, related_name='submissions', to='core.projectfeature')),
                ('selected_project_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.projecttype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
