# Generated by Django 6.0.1 on 2026-05-16 09:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_seed_project_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(help_text='e.g. "FY 2026-27"', max_length=50)),
                ('as_of_date', models.DateField(help_text='Balances are effective from this date')),
                ('cash_in_hand', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cash_in_account', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-as_of_date', '-created_at'],
            },
        ),
    ]
