# Generated by Django 6.0.1 on 2026-05-18 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_openingbalance'),
    ]

    operations = [
        migrations.AddField(
            model_name='openingbalance',
            name='accounts_receivable',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total outstanding from clients carried into this FY (preserved when invoices are wiped).', max_digits=14),
        ),
    ]
