# Generated by Django 6.0.1 on 2026-05-18 06:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_openingbalance_accounts_receivable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='quote_starting_number',
            field=models.IntegerField(default=1, help_text='Starting number for quotes (used when no quotes exist with the current prefix)'),
        ),
        migrations.CreateModel(
            name='FYResetEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ran_at', models.DateTimeField(auto_now_add=True)),
                ('invoices_wiped', models.IntegerField(default=0)),
                ('payments_wiped', models.IntegerField(default=0)),
                ('expenses_wiped', models.IntegerField(default=0)),
                ('leads_wiped', models.IntegerField(default=0)),
                ('outstanding_receivables', models.DecimalField(decimal_places=2, default=0, help_text='Sum of unpaid invoice balance_due at the moment of reset.', max_digits=14)),
                ('invoice_prefix_after', models.CharField(blank=True, max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('opening_balance', models.ForeignKey(blank=True, help_text='Opening balance active when the reset ran (carries receivables forward).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resets', to='core.openingbalance')),
                ('ran_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fy_resets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-ran_at'],
            },
        ),
    ]
