# Generated by Django 6.0.1 on 2026-05-18 07:39

from django.db import migrations, models


def set_not_applicable_for_zero_tax(apps, schema_editor):
    Invoice = apps.get_model('core', 'Invoice')
    Invoice.objects.filter(tax_amount=0).update(gst_filing_status='not_applicable')


def reverse_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_companysettings_quote_starting_number_fyresetevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='gst_filed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='gst_filing_status',
            field=models.CharField(choices=[('pending', 'Pending GST filing'), ('filed', 'Filed in GSTR'), ('not_applicable', 'GST not applicable')], default='pending', help_text='Tracks whether this invoice has been included in a GSTR filing.', max_length=20),
        ),
        migrations.RunPython(set_not_applicable_for_zero_tax, reverse_noop),
    ]
