# Generated by Django 6.0.1 on 2026-05-21 07:20

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_add_gst_filing_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. "Primary Current Account", "Joint Savings"', max_length=100)),
                ('account_type', models.CharField(choices=[('cash', 'Cash on Hand'), ('bank', 'Bank Account')], default='bank', max_length=10)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('account_number', models.CharField(blank=True, max_length=40)),
                ('ifsc', models.CharField(blank=True, max_length=20)),
                ('branch', models.CharField(blank=True, max_length=100)),
                ('upi_id', models.CharField(blank=True, max_length=100)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('opening_date', models.DateField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('is_primary_bank', models.BooleanField(default=False, help_text='Default bucket for non-cash Payment/Expense methods. Exactly one.')),
                ('is_cash', models.BooleanField(default=False, help_text='Default bucket for cash Payment/Expense. Exactly one.')),
                ('display_order', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='InternalTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Transfer date. May be future-dated for scheduled transfers.')),
                ('reference', models.CharField(blank=True, help_text='UPI ref / cheque no / transaction id', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internal_transfers', to=settings.AUTH_USER_MODEL)),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='core.bankaccount')),
                ('to_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='core.bankaccount')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('from_account', models.F('to_account')), _negated=True), name='internaltransfer_from_to_distinct'), models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='internaltransfer_amount_positive')],
            },
        ),
    ]
