# Generated by Django 6.0.1 on 2026-05-24 05:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0036_seed_bank_accounts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='e.g. "GST Registration Certificate", "Office Rental Agreement"', max_length=255)),
                ('document_type', models.CharField(choices=[('license', 'License'), ('registration', 'Registration'), ('agreement', 'Agreement'), ('partnership_deed', 'Partnership Deed'), ('insurance', 'Insurance'), ('other', 'Other')], default='other', max_length=20)),
                ('file', models.FileField(upload_to='company_docs/')),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('issuer', models.CharField(blank=True, help_text='Authority/issuer (e.g. "GST Department", "ABC Insurance Co")', max_length=255)),
                ('reference_number', models.CharField(blank=True, help_text='Doc / certificate / policy number', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('object_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_company_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['expiry_date', '-created_at'],
            },
        ),
    ]
