# Generated by Django 6.0.1 on 2026-05-24 08:40

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_partner_capitalcontribution'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. "Office rent advance", "Vehicle security deposit"', max_length=255)),
                ('asset_type', models.CharField(choices=[('rent_deposit', 'Rent / Office Deposit'), ('security_deposit', 'Security Deposit'), ('equipment', 'Equipment'), ('vehicle', 'Vehicle'), ('other', 'Other')], default='rent_deposit', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('acquired_date', models.DateField(default=django.utils.timezone.now)),
                ('counterparty', models.CharField(blank=True, help_text='Landlord / vendor / who holds the deposit', max_length=255)),
                ('expected_return_date', models.DateField(blank=True, help_text='When the deposit is expected to be refunded (leave blank for non-refundable assets)', null=True)),
                ('is_refundable', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck when the deposit has been refunded / asset disposed')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_active', 'expected_return_date', '-created_at'],
            },
        ),
    ]
