# Generated by Django 6.0.1 on 2026-06-04 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_companyasset'),
        ('crm', '0004_lead_lost_reason_alter_lead_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='crm.lead'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='core.client'),
        ),
    ]
