# Generated by Django 6.0.1 on 2026-08-29 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_dailytask'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='authorized_signature',
            field=models.FileField(blank=True, help_text='Signature image stamped on signed agreements. Transparent PNG works best.', upload_to='company/'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='company_seal',
            field=models.FileField(blank=True, help_text='Company seal or stamp shown beside the signature. Transparent PNG works best.', upload_to='company/'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='signatory_designation',
            field=models.CharField(blank=True, default='Authorized Representative', help_text='Printed under the signatory name', max_length=200),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='signatory_name',
            field=models.CharField(blank=True, help_text='Name printed under the company signature, e.g. Jobin Sebastian', max_length=200),
        ),
    ]
