# Generated by Django 6.0.1 on 2026-09-01 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_companysettings_authorized_signature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='payment_terms_custom',
            field=models.TextField(blank=True, help_text='Free-text payment terms, used when payment_terms is "custom"'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='payment_terms',
            field=models.CharField(blank=True, choices=[('50-50', '50% Advance, 50% on Completion'), ('30-30-40', '30% Advance, 30% Mid-project, 40% on Completion'), ('100-advance', '100% Advance'), ('100-completion', '100% on Completion'), ('custom', 'Custom')], default='50-50', max_length=50),
        ),
    ]
