# Generated by Django 6.0.1 on 2026-09-22 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_quote_payment_terms_custom_alter_quote_payment_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='non_gst_invoice_prefix',
            field=models.CharField(default='NG', help_text='Prefix for invoices without GST, which are numbered separately', max_length=10),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='non_gst_invoice_starting_number',
            field=models.IntegerField(default=1, help_text='Starting number for invoices without GST (used when none exist with the current prefix)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='renumbered_from',
            field=models.CharField(blank=True, help_text='The number this invoice had before it moved between the GST and no-GST series.', max_length=20),
        ),
    ]
