# Generated by Django 6.0.1 on 2026-09-26 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_invoice_payment_gst_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='amccontract',
            name='agreement_no',
            field=models.CharField(blank=True, editable=False, max_length=30),
        ),
        migrations.AddField(
            model_name='amccontract',
            name='covered_system',
            field=models.TextField(blank=True, help_text='Schedule A, one component per line: Component | Technology | URL / ID'),
        ),
        migrations.AddField(
            model_name='amccontract',
            name='extra_hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Rate for work outside the AMC; blank means it is quoted per job', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='amccontract',
            name='include_gst',
            field=models.BooleanField(default=True, help_text='Charge GST on top of the fee'),
        ),
        migrations.AddField(
            model_name='amccontract',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Annual amount as a % of the project value (typically 20-25); blank for a fixed amount', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='amccontract',
            name='plan',
            field=models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium')], default='standard', max_length=10),
        ),
    ]
