import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';

import 'firebase_options.dart'; // generated by flutterfire configure

// SOLUTION - lesson 7.4: Chat app, part 1 (setup and sign-in).
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  runApp(ChatApp(auth: AuthRepository(FirebaseAuth.instance)));
}

/// The only class that talks to FirebaseAuth. Widgets use this instead.
class AuthRepository {
  AuthRepository(this._auth);
  final FirebaseAuth _auth;

  Stream<User?> authStateChanges() => _auth.authStateChanges();

  Future<void> signIn(String email, String password) =>
      _auth.signInWithEmailAndPassword(email: email, password: password);

  Future<void> register(String email, String password) =>
      _auth.createUserWithEmailAndPassword(email: email, password: password);

  Future<void> signOut() => _auth.signOut();

  static String messageFor(FirebaseAuthException e) => switch (e.code) {
        'invalid-email' => 'That email address looks wrong.',
        'invalid-credential' || 'wrong-password' || 'user-not-found' => 'Wrong email or password.',
        'email-already-in-use' => 'An account already exists for that email.',
        'weak-password' => 'Choose a stronger password (at least 6 characters).',
        'too-many-requests' => 'Too many attempts. Try again later.',
        'network-request-failed' => 'No connection. Check your internet.',
        _ => 'Something went wrong. Please try again.',
      };
}

class ChatApp extends StatefulWidget {
  const ChatApp({super.key, required this.auth});
  final AuthRepository auth;
  @override
  State<ChatApp> createState() => _ChatAppState();
}

class _ChatAppState extends State<ChatApp> {
  // Created once, not in build (lesson 7.2).
  late final Stream<User?> _authStream = widget.auth.authStateChanges();
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Chat',
      theme: ThemeData(colorScheme: ColorScheme.fromSeed(seedColor: Colors.blue)),
      home: StreamBuilder<User?>(
        stream: _authStream,
        builder: (context, snapshot) {
          if (snapshot.connectionState == ConnectionState.waiting) {
            return const Scaffold(body: Center(child: CircularProgressIndicator()));
          }
          final user = snapshot.data;
          return user == null
              ? SignInPage(auth: widget.auth)
              : HomePage(auth: widget.auth, user: user);
        },
      ),
    );
  }
}

class SignInPage extends StatefulWidget {
  const SignInPage({super.key, required this.auth});
  final AuthRepository auth;
  @override
  State<SignInPage> createState() => _SignInPageState();
}

class _SignInPageState extends State<SignInPage> {
  final _email = TextEditingController();
  final _password = TextEditingController();
  bool _register = false;
  bool _busy = false;
  String? _error;
  @override
  void dispose() {
    _email.dispose();
    _password.dispose();
    super.dispose();
  }

  Future<void> _submit() async {
    setState(() {
      _busy = true;
      _error = null;
    });
    final email = _email.text.trim();
    final password = _password.text;
    try {
      if (_register) {
        await widget.auth.register(email, password);
      } else {
        await widget.auth.signIn(email, password);
      }
      // No navigation: the auth stream in ChatApp swaps this page.
    } on FirebaseAuthException catch (e) {
      if (mounted) setState(() => _error = AuthRepository.messageFor(e));
    } finally {
      if (mounted) setState(() => _busy = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    final action = _register ? 'Create account' : 'Sign in';
    return Scaffold(
      appBar: AppBar(title: Text(action)),
      body: ListView(
        padding: const EdgeInsets.all(24),
        children: [
          const Icon(Icons.forum, size: 64),
          const SizedBox(height: 24),
          TextField(
            controller: _email,
            keyboardType: TextInputType.emailAddress,
            autofillHints: const [AutofillHints.email],
            decoration: const InputDecoration(
                labelText: 'Email', prefixIcon: Icon(Icons.email_outlined)),
          ),
          const SizedBox(height: 12),
          TextField(
            controller: _password,
            obscureText: true,
            decoration: InputDecoration(
              labelText: 'Password',
              prefixIcon: const Icon(Icons.lock_outline),
              errorText: _error,
            ),
          ),
          const SizedBox(height: 24),
          FilledButton(
            onPressed: _busy ? null : _submit,
            child: _busy
                ? const SizedBox.square(
                    dimension: 20, child: CircularProgressIndicator(strokeWidth: 2))
                : Text(action),
          ),
          TextButton(
            onPressed: _busy ? null : () => setState(() => _register = !_register),
            child: Text(_register ? 'I already have an account' : 'Create an account'),
          ),
        ],
      ),
    );
  }
}

class HomePage extends StatelessWidget {
  const HomePage({super.key, required this.auth, required this.user});
  final AuthRepository auth;
  final User user;
  @override
  Widget build(BuildContext context) {
    final email = user.email ?? 'unknown';
    return Scaffold(
      appBar: AppBar(title: const Text('Chat'), actions: [
        IconButton(tooltip: 'Sign out', icon: const Icon(Icons.logout), onPressed: auth.signOut),
      ]),
      body: Center(
        child: Column(mainAxisSize: MainAxisSize.min, children: [
          CircleAvatar(radius: 32, child: Text(email[0].toUpperCase())),
          const SizedBox(height: 12),
          Text('Signed in as $email'),
          const SizedBox(height: 4),
          Text('Messages arrive in lesson 7.5', style: Theme.of(context).textTheme.bodySmall),
        ]),
      ),
    );
  }
}
