# Generated by Django 5.0.1 on 2026-01-25 06:27

import django.db.models.deletion
import retailease.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('licensing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('legal_name', models.CharField(blank=True, max_length=200)),
                ('business_type', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('address_line1', models.CharField(blank=True, max_length=200)),
                ('address_line2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('gst_number', models.CharField(blank=True, max_length=20)),
                ('pan_number', models.CharField(blank=True, max_length=20)),
                ('currency_code', models.CharField(default='INR', max_length=3)),
                ('currency_symbol', models.CharField(default='₹', max_length=5)),
                ('date_format', models.CharField(default='DD/MM/YYYY', max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='business_logos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('license', models.ForeignKey(help_text='The license this business is registered under', on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to='licensing.license')),
            ],
            options={
                'verbose_name': 'Business',
                'verbose_name_plural': 'Businesses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="e.g., 'Counter 1', 'Main POS'", max_length=100)),
                ('description', models.TextField(blank=True)),
                ('device_name', models.CharField(blank=True, max_length=200)),
                ('device_type', models.CharField(blank=True, max_length=50)),
                ('os_info', models.CharField(blank=True, max_length=100)),
                ('app_version', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary counter for the business')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('sync_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activation', models.OneToOneField(help_text='The license activation for this counter', on_delete=django.db.models.deletion.CASCADE, related_name='counter', to='licensing.licenseactivation')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counters', to='retailease.business')),
            ],
            options={
                'verbose_name': 'Counter',
                'verbose_name_plural': 'Counters',
                'ordering': ['business', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=retailease.models.backup_upload_path)),
                ('filename', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField(default=0, help_text='Size in bytes')),
                ('checksum', models.CharField(blank=True, help_text='SHA-256 checksum', max_length=64)),
                ('is_encrypted', models.BooleanField(default=True)),
                ('encryption_version', models.CharField(default='1.0', max_length=10)),
                ('backup_type', models.CharField(choices=[('manual', 'Manual Backup'), ('auto', 'Automatic Backup'), ('pre_restore', 'Pre-Restore Backup')], default='manual', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('uploading', 'Uploading'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('app_version', models.CharField(blank=True, max_length=20)),
                ('db_version', models.IntegerField(default=1, help_text='Database schema version')),
                ('record_counts', models.JSONField(blank=True, default=dict, help_text="Summary of records: {'products': 100, 'invoices': 50, ...}")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backups', to='retailease.business')),
                ('counter', models.ForeignKey(blank=True, help_text='The counter that created this backup', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backups', to='retailease.counter')),
            ],
            options={
                'verbose_name': 'Backup',
                'verbose_name_plural': 'Backups',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='APIToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name', models.CharField(blank=True, help_text='Token name/description', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens', to='licensing.license')),
                ('counter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens', to='retailease.counter')),
            ],
            options={
                'verbose_name': 'API Token',
                'verbose_name_plural': 'API Tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sync_type', models.CharField(choices=[('full', 'Full Sync'), ('incremental', 'Incremental Sync'), ('conflict_resolution', 'Conflict Resolution')], default='incremental', max_length=20)),
                ('sync_direction', models.CharField(choices=[('upload', 'Upload (Counter → Server)'), ('download', 'Download (Server → Counter)'), ('bidirectional', 'Bidirectional')], default='upload', max_length=20)),
                ('status', models.CharField(choices=[('started', 'Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('partial', 'Partial Success')], default='started', max_length=20)),
                ('records_uploaded', models.IntegerField(default=0)),
                ('records_downloaded', models.IntegerField(default=0)),
                ('conflicts_detected', models.IntegerField(default=0)),
                ('conflicts_resolved', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='retailease.business')),
                ('counter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='retailease.counter')),
            ],
            options={
                'verbose_name': 'Sync Log',
                'verbose_name_plural': 'Sync Logs',
                'ordering': ['-started_at'],
            },
        ),
    ]
