# Generated by Django 5.0.1 on 2026-01-25 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailease', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='default', max_length=50, unique=True)),
                ('google_client_id', models.CharField(blank=True, help_text='Google OAuth 2.0 Client ID for desktop apps', max_length=200)),
                ('google_client_id_ios', models.CharField(blank=True, help_text='Google OAuth 2.0 Client ID for iOS (if different)', max_length=200)),
                ('google_client_id_android', models.CharField(blank=True, help_text='Google OAuth 2.0 Client ID for Android (if different)', max_length=200)),
                ('google_reversed_client_id', models.CharField(blank=True, help_text='Reversed Client ID for iOS URL scheme', max_length=200)),
                ('google_drive_enabled', models.BooleanField(default=True, help_text='Enable Google Drive backup feature')),
                ('server_backup_enabled', models.BooleanField(default=True, help_text='Enable Server backup feature')),
                ('local_backup_enabled', models.BooleanField(default=True, help_text='Enable Local backup feature')),
                ('min_app_version', models.CharField(default='1.0.0', help_text='Minimum required app version', max_length=20)),
                ('latest_app_version', models.CharField(default='1.0.0', help_text='Latest available app version', max_length=20)),
                ('app_update_url', models.URLField(blank=True, help_text='URL to download app update')),
                ('force_update', models.BooleanField(default=False, help_text='Force users to update if below min_app_version')),
                ('maintenance_mode', models.BooleanField(default=False, help_text='Enable maintenance mode (shows message to users)')),
                ('maintenance_message', models.TextField(blank=True, help_text='Message to show during maintenance')),
                ('support_email', models.EmailField(default='support@ralfizdigital.in', max_length=254)),
                ('support_phone', models.CharField(blank=True, max_length=20)),
                ('support_whatsapp', models.CharField(blank=True, max_length=20)),
                ('terms_url', models.URLField(blank=True)),
                ('privacy_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'App Configuration',
                'verbose_name_plural': 'App Configuration',
            },
        ),
    ]
