# Generated by Django 5.0.1 on 2026-01-25 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retailease', '0002_add_app_config'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppConfig',
        ),
    ]
