# Generated by Django 6.0.1 on 2026-01-22 08:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='RetailEase Pro', max_length=100)),
                ('private_key', models.TextField(help_text='PEM encoded private key (keep secret!)')),
                ('public_key', models.TextField(help_text='PEM encoded public key (embed in app)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'License Key Pair',
                'verbose_name_plural': 'License Key Pairs',
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_company', models.CharField(blank=True, max_length=200)),
                ('customer_phone', models.CharField(blank=True, max_length=20)),
                ('license_type', models.CharField(choices=[('trial', 'Trial (30 days)'), ('basic', 'Basic (1 year)'), ('professional', 'Professional (1 year)'), ('enterprise', 'Enterprise (1 year)'), ('lifetime', 'Lifetime')], default='basic', max_length=20)),
                ('machine_id', models.CharField(blank=True, help_text='Hardware fingerprint (filled on activation)', max_length=64)),
                ('max_activations', models.PositiveIntegerField(default=1)),
                ('current_activations', models.PositiveIntegerField(default=0)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('revoked', 'Revoked'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('license_code', models.TextField(blank=True, help_text='The signed license code to give to customer')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key_pair', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='licenses', to='licensing.licensekey')),
            ],
            options={
                'verbose_name': 'License',
                'verbose_name_plural': 'Licenses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LicenseActivation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('machine_id', models.CharField(max_length=64)),
                ('machine_name', models.CharField(blank=True, max_length=200)),
                ('activated_at', models.DateTimeField(auto_now_add=True)),
                ('last_check', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activations', to='licensing.license')),
            ],
            options={
                'ordering': ['-activated_at'],
                'unique_together': {('license', 'machine_id')},
            },
        ),
    ]
