# Generated by Django 5.0.1 on 2026-01-25 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_companysettings_google_client_id_and_more'),
        ('licensing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Link this license to an existing client', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licenses', to='core.client'),
        ),
    ]
