# Generated by Django 6.0.1 on 2026-01-29 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0002_license_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='auto_renew',
            field=models.BooleanField(default=False, help_text='Auto-renew when payment received'),
        ),
        migrations.AddField(
            model_name='license',
            name='billing_cycle',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly'), ('lifetime', 'Lifetime (One-time)')], default='yearly', max_length=20),
        ),
        migrations.AddField(
            model_name='license',
            name='grace_period_days',
            field=models.PositiveIntegerField(default=7, help_text='Days after expiry before full lockout'),
        ),
        migrations.AddField(
            model_name='license',
            name='last_renewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='license',
            name='renewal_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
