# Generated by Django 6.0.1 on 2026-03-21 13:03

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0019_make_invoice_number_editable'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymLicense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gym_name', models.CharField(help_text='Name of the gym', max_length=255)),
                ('gym_owner_name', models.CharField(blank=True, max_length=255)),
                ('gym_email', models.EmailField(help_text='Primary contact email', max_length=254)),
                ('gym_phone', models.CharField(blank=True, max_length=20)),
                ('gym_address', models.TextField(blank=True)),
                ('license_key', models.CharField(db_index=True, help_text='Unique license key sent to the gym (GYM-XXXX-XXXX-XXXX)', max_length=64, unique=True)),
                ('api_domain', models.CharField(help_text="The gym's API domain (e.g., api.fitzone.com). License is bound to this domain.", max_length=255, unique=True)),
                ('landing_domain', models.CharField(blank=True, help_text='Landing page domain', max_length=255)),
                ('license_type', models.CharField(choices=[('trial', 'Trial (30 days)'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('half_yearly', 'Half Yearly'), ('yearly', 'Yearly'), ('lifetime', 'Lifetime')], default='yearly', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('suspended', 'Suspended'), ('revoked', 'Revoked')], db_index=True, default='active', max_length=20)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('half_yearly', 'Half Yearly'), ('yearly', 'Yearly'), ('lifetime', 'Lifetime')], default='yearly', max_length=20)),
                ('auto_renew', models.BooleanField(default=False)),
                ('grace_period_days', models.PositiveIntegerField(default=7)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField()),
                ('last_renewed_at', models.DateTimeField(blank=True, null=True)),
                ('renewal_count', models.PositiveIntegerField(default=0)),
                ('enabled_modules', models.JSONField(blank=True, default=list, help_text='List of enabled module keys. Empty = all modules enabled.')),
                ('max_members', models.PositiveIntegerField(default=0, help_text='Max members allowed. 0 = unlimited.')),
                ('max_trainers', models.PositiveIntegerField(default=0, help_text='Max trainers allowed. 0 = unlimited.')),
                ('server_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('deployment_notes', models.TextField(blank=True)),
                ('last_check_at', models.DateTimeField(blank=True, help_text='Last time gym validated license', null=True)),
                ('last_check_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('total_checks', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, help_text='Link to Ralfiz client record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gympro_licenses', to='core.client')),
            ],
            options={
                'verbose_name': 'GymPro License',
                'verbose_name_plural': 'GymPro Licenses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GymLicenseLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event', models.CharField(choices=[('validate', 'Validate'), ('check', 'Check'), ('renew', 'Renew'), ('expire', 'Expire'), ('revoke', 'Revoke'), ('suspend', 'Suspend'), ('reactivate', 'Reactivate'), ('create', 'Create'), ('update', 'Update'), ('domain_mismatch', 'Domain Mismatch')], max_length=30)),
                ('status', models.CharField(max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('domain', models.CharField(blank=True, max_length=255)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='gympro_licensing.gymlicense')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
