# Generated by Django 6.0.1 on 2026-04-03 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_client_user'),
        ('crm', '0002_followup_leadactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Client created when lead is converted', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_leads', to='core.client'),
        ),
    ]
