# Generated by Django 6.0.1 on 2026-06-03 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_lead_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='lost_reason',
            field=models.CharField(blank=True, choices=[('price', 'Price / Budget too high'), ('no_budget', 'No budget'), ('competitor', 'Chose a competitor'), ('no_response', 'No response / went cold'), ('not_interested', 'Not interested'), ('bad_timing', 'Bad timing'), ('not_a_fit', 'Not a fit / wrong audience'), ('duplicate', 'Duplicate lead'), ('other', 'Other')], help_text='Why the lead was lost/unqualified (set when status is lost or unqualified)', max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('interested', 'Interested'), ('qualified', 'Qualified'), ('demo_scheduled', 'Demo Scheduled'), ('demo_completed', 'Demo Completed'), ('proposal_sent', 'Proposal Sent'), ('negotiation', 'Negotiation'), ('follow_up', 'Follow-up'), ('on_hold', 'On Hold'), ('converted', 'Converted'), ('unqualified', 'Unqualified'), ('lost', 'Lost')], default='new', max_length=20),
        ),
    ]
