# Generated by Django 6.0.1 on 2026-06-09 05:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_leadreferencelink'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadQuoteAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='e.g. "Website redesign quote v2"', max_length=200)),
                ('file', models.FileField(upload_to='lead_quotes/')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Quoted amount (optional)', max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_lead_quote_attachments', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_attachments', to='crm.lead')),
            ],
            options={
                'verbose_name': 'Lead Quote Attachment',
                'verbose_name_plural': 'Lead Quote Attachments',
                'ordering': ['-created_at'],
            },
        ),
    ]
