# Generated by Django 6.0.1 on 2026-09-27 05:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_sha256', models.CharField(max_length=64)),
                ('content_version', models.CharField(blank=True, max_length=20)),
                ('counts', models.JSONField(default=dict)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-imported_at'],
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('weight', models.CharField(max_length=50)),
                ('blurb', models.TextField(blank=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseFile',
            fields=[
                ('id', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('zip_path', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('track_ids', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('level', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=200)),
                ('outline_date', models.CharField(max_length=50)),
                ('order_hint', models.CharField(max_length=100)),
                ('blurb', models.TextField()),
                ('facts', models.JSONField(default=list)),
                ('tool', models.CharField(max_length=200)),
                ('guide_url', models.URLField()),
                ('note', models.TextField()),
                ('data_file_ids', models.JSONField(default=list)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('content_version', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('num', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=300)),
                ('minutes', models.PositiveSmallIntegerField(default=0)),
                ('summary_html', models.TextField(blank=True)),
                ('content_html', models.TextField(blank=True)),
                ('terms', models.JSONField(default=list)),
                ('exam_tip', models.TextField(blank=True)),
                ('widget', models.CharField(blank=True, max_length=20)),
                ('sorter', models.JSONField(blank=True, null=True)),
                ('lab_steps', models.JSONField(default=list)),
                ('lab_check', models.JSONField(default=list)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='academy.domain')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='academy.track')),
            ],
            options={
                'ordering': ['track__sort_order', 'domain__sort_order', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='LessonFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='academy.exercisefile')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_files', to='academy.lesson')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('lesson', 'Lesson quiz'), ('bank', 'Question bank')], default='lesson', max_length=10)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('question', models.TextField()),
                ('options', models.JSONField(default=list)),
                ('answer', models.PositiveSmallIntegerField()),
                ('explanation', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='academy.lesson')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='academy.track')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('batch', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('last_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='academy.lesson')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__first_name', 'user__username'],
            },
        ),
        migrations.CreateModel(
            name='TestAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_ids', models.JSONField(default=list)),
                ('answers', models.JSONField(default=dict)),
                ('correct_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academy_tests', to=settings.AUTH_USER_MODEL)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='academy.track')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='domain',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='academy.track'),
        ),
        migrations.CreateModel(
            name='LabProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticked_steps', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academy_lab_progress', to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='academy.lesson')),
            ],
            options={
                'unique_together': {('user', 'lesson')},
            },
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_choice', models.PositiveSmallIntegerField()),
                ('ever_correct', models.BooleanField(default=False)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='academy.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academy_quiz_answers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'question')},
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.CharField(blank=True, max_length=100)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academy.student')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academy.track')),
            ],
            options={
                'ordering': ['track__sort_order'],
                'unique_together': {('student', 'track')},
            },
        ),
    ]
