# Generated by Django 6.0.1 on 2026-09-27 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_student_seen_badges_student_unlock_all_learningday'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
