# Generated by Django 6.0.1 on 2026-09-28 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_lesson_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='video_playlist',
            field=models.URLField(blank=True, max_length=300),
        ),
    ]
