# Generated by Django 6.0.1 on 2026-09-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0005_pl900_video_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='category',
            field=models.CharField(choices=[('certification', 'Microsoft certification'), ('development', 'App development')], default='certification', max_length=20),
        ),
        migrations.AddField(
            model_name='track',
            name='offer_price',
            field=models.PositiveIntegerField(blank=True, help_text='Rupees. Shown with the full price struck through.', null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='price',
            field=models.PositiveIntegerField(blank=True, help_text='Rupees. Empty hides the price; 0 shows Free.', null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='price_note',
            field=models.CharField(blank=True, help_text='e.g. One-time fee · lifetime access', max_length=120),
        ),
    ]
