# Generated by Django 6.0.1 on 2026-09-28 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0006_track_pricing_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='mocks',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
