# Generated by Django 6.0.1 on 2026-09-29 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0007_lesson_mocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='plays',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
