# Generated by Django 6.0.1 on 2026-09-30 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0008_lesson_plays'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='solvers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='question',
            name='key',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='question',
            name='kind',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='question',
            name='paper',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='stem',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='paper',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='time_limit',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='exam',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='track',
            name='category',
            field=models.CharField(choices=[('certification', 'Microsoft certification'), ('development', 'App development'), ('exam', 'Competitive exam')], default='certification', max_length=20),
        ),
    ]
