# Generated by Django 6.0.1 on 2026-09-28 10:16

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0046_amc_agreement_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='RalfPOSLicense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shop_name', models.CharField(max_length=255)),
                ('owner_name', models.CharField(blank=True, max_length=255)),
                ('shop_email', models.EmailField(blank=True, max_length=254)),
                ('shop_phone', models.CharField(blank=True, max_length=30)),
                ('shop_address', models.TextField(blank=True)),
                ('country', models.CharField(blank=True, help_text='e.g. India, UAE, Saudi Arabia', max_length=40)),
                ('license_key', models.CharField(db_index=True, help_text='Unique licence key (POS-XXXX-XXXX-XXXX)', max_length=64, unique=True)),
                ('api_domain', models.CharField(blank=True, default='', help_text="The shop's RalfPOS address. Empty until the first activation, then bound.", max_length=255)),
                ('license_type', models.CharField(choices=[('trial', 'Trial (30 days)'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('half_yearly', 'Half Yearly'), ('yearly', 'Yearly'), ('lifetime', 'Lifetime')], default='yearly', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('suspended', 'Suspended'), ('revoked', 'Revoked')], db_index=True, default='active', max_length=20)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('half_yearly', 'Half Yearly'), ('yearly', 'Yearly'), ('lifetime', 'Lifetime')], default='yearly', max_length=20)),
                ('grace_period_days', models.PositiveIntegerField(default=7)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField()),
                ('last_renewed_at', models.DateTimeField(blank=True, null=True)),
                ('renewal_count', models.PositiveIntegerField(default=0)),
                ('enabled_modules', models.JSONField(blank=True, default=list, help_text='Add-on module keys this shop has paid for. Empty = basic app only.')),
                ('max_counters', models.PositiveIntegerField(default=0, help_text='0 = unlimited')),
                ('server_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('app_version', models.CharField(blank=True, max_length=40)),
                ('deployment_notes', models.TextField(blank=True)),
                ('last_check_at', models.DateTimeField(blank=True, null=True)),
                ('last_check_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('total_checks', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, help_text='Link to Ralfiz client record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ralfpos_licenses', to='core.client')),
            ],
            options={
                'verbose_name': 'RalfPOS License',
                'verbose_name_plural': 'RalfPOS Licenses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RalfPOSLicenseLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event', models.CharField(choices=[('activate', 'Activate'), ('check', 'Check'), ('renew', 'Renew'), ('expire', 'Expire'), ('revoke', 'Revoke'), ('suspend', 'Suspend'), ('reactivate', 'Reactivate'), ('create', 'Create'), ('update', 'Update'), ('domain_mismatch', 'Domain Mismatch')], max_length=30)),
                ('status', models.CharField(max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('domain', models.CharField(blank=True, max_length=255)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='ralfpos_licensing.ralfposlicense')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
